- name: Add flathub repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpak packages
  community.general.flatpak:
    name: "{{ flatpak_apps }}"
